apiVersion: v1
kind: Service
metadata:
  name: 'video-conferencing-service'
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app: 'video-conferencing-service'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-conferencing-service
  labels:
    app: video-conferencing-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-conferencing-service
  template:
    metadata:
      labels:
        app: video-conferencing-service
    spec:
      tolerations:
        - key: 'type'
          operator: 'Equal'
          value: 'hackathon-spot'
          effect: 'NoSchedule'
      containers:
        - name: video-conferencing-service
          image: '{{ CONTAINER_IMAGE }}'
          imagePullPolicy: Always

          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10

          startupProbe:
            failureThreshold: 5
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10

          resources:
            limits:
              memory: '1024Mi'
              cpu: '1'
            requests:
              memory: '512Mi'
              cpu: '375m'
          ports:
            - containerPort: 3000
          env:
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: hackathon-secret
                  key: LOG_LEVEL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: hackathon-secret
                  key: JWT_SECRET
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: hackathon-secret
                  key: JWT_ISSUER
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: hackathon-secret
                  key: NODE_ENV
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: hackathon-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: hackathon-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: hackathon-secret
                  key: DB_USER
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: hackathon-secret
                  key: VIDEO-CONFERENCING-SERVICE_DB_DATABASE
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: hackathon-secret
                  key: VIDEO_SERVICE_DB_SCHEMA
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hackathon-secret
                  key: DB_PASSWORD
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: hackathon-secret
                  key: REDIS_URL
            - name: VONAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hackathon-secret
                  key: VONAGE_API_KEY
            - name: VONAGE_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: hackathon-secret
                  key: VONAGE_API_SECRET